### ISSUE TITLE
Joyride throws an error when activated in a window with no folder

### ISSUE THREAD

**Issue by maxrothman** [BetterThanTomorrow/joyride#51]
When joyride is activated in a VSCode window with no folders added to the workspace, it throws this error:

```
[2022-05-10 15:50:53.966] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at <path/to>/joyride/out/js/cljs-runtime/joyride/life_cycle.cljs:16:37
    at <path/to>/joyride/out/joyride.js:70:44
    at <path/to>/joyride/out/joyride.js:1593:1
    at <path/to>/repos/joyride/out/joyride.js:5:26
    at Object.<anonymous> (/Users/maxrothman/repos/joyride/out/joyride.js:9:3)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
    at Object..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at node:internal/modules/cjs/loader:876:12
    at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13343)
    at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:32307)
    at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:28750)
    at Function._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:61719)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/maxrothman/repos/joyride/extension.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
    at Object..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at node:internal/modules/cjs/loader:876:12
    at Function.<anonymous> (node:electron/js2c/asar_bundle:5:13343)
    at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:32307)
    at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:28750)
    at Function._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:61719)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.r [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at m._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:30353)
    at m._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:14751)
    at m._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:13702)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
    at _waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
    at _initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:7486)
```

Digging around a little more, it appears that `vscode/workspace.rootPath` is undefined [in life_cycle.cljs](https://github.com/maxrothman/joyride/blob/148d2afd9ed4e2250ef8eb05e93fc86b31ca6f39/src/main/joyride/life_cycle.cljs#L16).

Discussed in: https://clojurians.slack.com/archives/C03DPCLCV9N/p1652212180463169

**Comment by PEZ** [comment]
VS Code w/o a folder is not a truly happy VS Code. But of course Joyride should not throw errors like this in that situation. I guess this might be an issue also with the **Run Workspace Script** command.
